# Generated by Django 5.1.3 on 2024-11-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('patente', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.DateTimeField(null=True)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('tarifa', models.PositiveIntegerField()),
                ('total_pagado', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.estado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculos')),
            ],
        ),
    ]
