# Generated by Django 5.1.3 on 2024-11-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('patente', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('hora_salida', models.DateTimeField(null=True)),
                ('total_pagar', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('tarifa', models.PositiveIntegerField()),
            ],
        ),
    ]
