# Generated by Django 5.1.3 on 2024-12-03 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registroestacionamiento',
            name='estado',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.estado'),
        ),
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tarifa'),
        ),
    ]
