# Generated by Django 5.1.3 on 2024-11-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(max_length=25),
        ),
    ]
