# Generated by Django 5.1.3 on 2024-12-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tarifa_remove_registroestacionamiento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
