# Generated by Django 5.1.3 on 2024-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_registroestacionamiento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='registro',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
