# Generated by Django 5.1.3 on 2024-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vehiculos_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='registro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
