# Generated by Django 5.1.3 on 2024-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_vehiculos_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='tarifa',
            field=models.PositiveIntegerField(),
        ),
    ]
